### ISSUE TITLE
Change Font?

### ISSUE THREAD

**Issue by ghost** [lmgonzalves/letters#1]
http://tympanus.net/codrops/2016/03/02/creative-svg-letter-animations/
Firstly, Thank you very much
It would be also to show you how to change the fonts in your article.
Example : chair "n y" it would be great if the design changed in funds. How Can I do this

(translate) :)

**Comment by lmgonzalves** [comment]
Sorry, but I don't understand what you mean :(
Can you explain a little better what is your issue?

**Comment by ghost** [comment]
Sory man image ;

http://i.hizliresim.com/VaXn3y.png

**Comment by lmgonzalves** [comment]
Now I can understand perfectly :)
So, you should fork this repo, and make some changes in `initAlphabet` function inside `letters.js`.

1- Set letter `n` to:

``` js
'n': {
    svg: svgSmall,
        paths: [circleCenter, lineLeft, lineRight],
        initial: [{begin: '-60%', end: '-60%'}, {begin: '90%', end: '90%'}, {begin: '10%', end: '10%'}],
        final: [{begin: '-25%', end: '25%'}, {begin: p50minusRW, end: p50plusRW}, {begin: '50%', end: p50plusRW}]
},
```

2- Set letter `y` to:

``` js
'y': {
    svg: svgSmall,
        paths: [circleCenter, circleGY, lineRight, lineLeft],
        initial: [{begin: '1', end: '1'}, {begin: '1', end: '1'}, {begin: p50minusRW, end: p50minusRW}, {begin: '20%', end: '20%'}],
        final: [{begin: '-75%', end: '-25% + 1'}, {begin: '25% - 1', end: '50%'}, {begin: p50minusRW, end: p50plusRW}, {begin: p50minusRW, end: '50%'}]
},
```

[DEMO](https://jsfiddle.net/lmgonzalves/swz5f11q/1/)

**Comment by ghost** [comment]
thank you :)
