### ISSUE TITLE
Onload

### ISSUE THREAD

**Issue by ghost** [lmgonzalves/letters#2]
How can one get the effects to work on load ? Thank you. Great work.

**Comment by lmgonzalves** [comment]
Thanks!
Of course it’s possible :) See this simple (and unstyled) [DEMO](http://jsfiddle.net/lmgonzalves/uqrof22j/1/).

**Comment by ghost** [comment]
Great! But how does one stop it from disappearing after loading?  Just
loading it on load and staying that way.

Thanks.
Sorry for replying through mail & asking too many questions. Just really
love the design

**Comment by lmgonzalves** [comment]
Don't worry, I'm glad to help :)
You only need this:

``` js
(function(){
    var el = document.querySelector('.text');
    var text = new Letters(el);
    text.show();
})();
```

[DEMO](http://jsfiddle.net/lmgonzalves/uqrof22j/2/)

If you have any other issue, please let me know. But you should [read the article](http://tympanus.net/codrops/2016/03/02/creative-svg-letter-animations/) again for documentation and to know how to to get the best of the library :)
Thanks!

**Comment by ghost** [comment]
Thanks a lot

**Comment by ghost** [comment]
Hello Alves,

I'm a JS rookie and i can't get the file on the Js Fiddle as .zip . Please
can you help with that? Will appreciate a lot.
Thanks

**Comment by lmgonzalves** [comment]
I'm afraid that jsfiddle don't allow download demo as `.zip` file.
You have to recreate it manuallly, but this time I've done this for you :)
[demo.zip](https://github.com/lmgonzalves/letters/files/165208/demo.zip)

**Comment by ghost** [comment]
Thanks!
