### ISSUE TITLE
I can use it on my project

### ISSUE THREAD

**Issue by dalisoft** [lmgonzalves/letters#5]
Hi and thanks to amazing project. I can use this app on my project without fee is this premium?

**Comment by lmgonzalves** [comment]
Thanks for the kind words :)
And yes, you can use it freely in your projects ([MIT license](https://github.com/lmgonzalves/letters/blob/master/LICENSE)).

**Comment by dalisoft** [comment]
I want make it as my plugin for my new app maybe premium. This plugin would be great. I credit to github or codrops article

**Comment by lmgonzalves** [comment]
Make sure you read the [Codrops license](http://tympanus.net/codrops/licensing/) as well.

**Comment by dalisoft** [comment]
I read codrops license and making plugin for demos isnt allowed
